version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker --version 
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m2m0x2o3
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodepipeline-devopspo .
      - docker tag nodepipeline-devopspo:latest public.ecr.aws/m2m0x2o3/nodepipeline-devopspo:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/m2m0x2o3/nodepipeline-devopspo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nodepipeline-devops","imageUri":"%s"}]' public.ecr.aws/m2m0x2o3/nodepipeline-devopspo:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: 
      - imagedefinitions.json